apiVersion: v2
appVersion: 2.0.3
description: Helm chart for deploying Higress gateways
icon: https://higress.io/img/higress_logo_small.png
home: http://higress.io/
keywords:
- higress
- gateways
name: higress
sources:
- http://github.com/alibaba/higress
dependencies:
- name: higress-core
  repository: "file://../core"
  version: 2.0.3
- name: higress-console
  repository: "https://higress.io/helm-charts/"
  version: 1.4.5
type: application
version: 2.0.3
