apiVersion: v2
appVersion: 1.1.0
description: Helm chart for deploying higress gateways
icon: https://higress.io/img/higress_logo_small.png
home: http://higress.io/
keywords:
- higress
- gateways
name: higress-core
sources:
- http://github.com/alibaba/higress
type: application
version: 1.1.0
