apiVersion: v2
appVersion: 2.1.0
description: Helm chart for deploying higress gateways
icon: https://higress.io/img/higress_logo_small.png
home: http://higress.io/
keywords:
  - higress
  - gateways
name: higress-core
sources:
  - http://github.com/alibaba/higress
dependencies:
  - condition: global.enableRedis
    name: redis
    repository: "file://../redis"
    version: 0.0.1
type: application
version: 2.1.0
